// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// Obtain all chat themes associated to owned collectible gifts
/// See <a href="https://corefork.telegram.org/method/account.getUniqueGiftChatThemes" />
///</summary>
[TlObject(0xfe74ef9f)]
public sealed class RequestGetUniqueGiftChatThemes : IRequest<MyTelegram.Schema.Account.IChatThemes>
{
    public uint ConstructorId => 0xfe74ef9f;
    
    ///<summary>
    /// Pagination offset
    ///</summary>
    public int Offset { get; set; }
    
    ///<summary>
    /// Pagination limit
    ///</summary>
    public int Limit { get; set; }
    
    ///<summary>
    /// Hash for caching
    ///</summary>
    public long Hash { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Offset);
        writer.Write(Limit);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Offset = buffer.ReadInt32();
        Limit = buffer.ReadInt32();
        Hash = buffer.ReadInt64();
    }
}
