// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// Available chat themes
/// See <a href="https://corefork.telegram.org/constructor/account.chatThemes" />
///</summary>
[TlObject(0x16484857)]
public sealed class TAccountChatThemes : IChatThemes
{
    public uint ConstructorId => 0x16484857;
    
    ///<summary>
    /// Flags
    ///</summary>
    public int Flags { get; set; }
    
    ///<summary>
    /// Hash for caching
    ///</summary>
    public long Hash { get; set; }
    
    ///<summary>
    /// Chat themes
    ///</summary>
    public TVector<IChatTheme> Themes { get; set; }
    
    ///<summary>
    /// Chats
    ///</summary>
    public TVector<IChat> Chats { get; set; }
    
    ///<summary>
    /// Users
    ///</summary>
    public TVector<IUser> Users { get; set; }
    
    ///<summary>
    /// Next offset for pagination
    ///</summary>
    public int? NextOffset { get; set; }

    public void ComputeFlag()
    {
        if (NextOffset.HasValue) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Hash);
        writer.Write(Themes);
        writer.Write(Chats);
        writer.Write(Users);
        if (Flags.IsBitSet(0)) { writer.Write(NextOffset.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Hash = buffer.ReadInt64();
        Themes = buffer.Read<TVector<IChatTheme>>();
        Chats = buffer.Read<TVector<IChat>>();
        Users = buffer.Read<TVector<IUser>>();
        if (Flags.IsBitSet(0)) { NextOffset = buffer.ReadInt32(); }
    }
}
