// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// The available chat themes were not modified
/// See <a href="https://corefork.telegram.org/constructor/account.chatThemesNotModified" />
///</summary>
[TlObject(0xe011e1c4)]
public sealed class TAccountChatThemesNotModified : IChatThemes
{
    public uint ConstructorId => 0xe011e1c4;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
