// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Chat theme
/// See <a href="https://corefork.telegram.org/constructor/chatTheme" />
///</summary>
[TlObject(0xc3dffc04)]
public sealed class TChatTheme : IChatTheme
{
    public uint ConstructorId => 0xc3dffc04;
    
    ///<summary>
    /// Theme emoticon
    ///</summary>
    public string Emoticon { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Emoticon);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Emoticon = buffer.ReadString();
    }
}
